### ISSUE TITLE
OMV-Extra install is not working (OMV 5)

### ISSUE THREAD

**Issue by NoxInmortus** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#45]
Hello :

```
wget -O - https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/install | bash
--2020-09-05 16:01:26--  https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/install
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/OpenMediaVault-Plugin-Developers/packages/master/install [following]
--2020-09-05 16:01:26--  https://raw.githubusercontent.com/OpenMediaVault-Plugin-Developers/packages/master/install
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.120.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.120.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1067 (1.0K) [text/plain]
Saving to: ‘STDOUT’

-                                         100%[====================================================================================>]   1.04K  --.-KB/s    in 0s      

2020-09-05 16:01:26 (9.85 MB/s) - written to stdout [1067/1067]

5
Downloading omv-extras.org plugin for openmediavault 5.x ...
Updating repos before installing...
[...]
Install prerequisites...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dirmngr is already the newest version (2.2.12-1+deb10u1).
gnupg is already the newest version (2.2.12-1+deb10u1).
0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.
--2020-09-05 16:01:39--  https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master//openmediavault-omvextrasorg_latest_all5.deb
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/OpenMediaVault-Plugin-Developers/packages/master/openmediavault-omvextrasorg_latest_all5.deb [following]
--2020-09-05 16:01:40--  https://raw.githubusercontent.com/OpenMediaVault-Plugin-Developers/packages/master/openmediavault-omvextrasorg_latest_all5.deb
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.120.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.120.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 72740 (71K) [application/octet-stream]
Saving to: ‘openmediavault-omvextrasorg_latest_all5.deb’

openmediavault-omvextrasorg_latest_all5.d 100%[====================================================================================>]  71.04K  --.-KB/s    in 0.01s   

2020-09-05 16:01:40 (6.16 MB/s) - ‘openmediavault-omvextrasorg_latest_all5.deb’ saved [72740/72740]

Selecting previously unselected package openmediavault-omvextrasorg.
(Reading database ... 52721 files and directories currently installed.)
Preparing to unpack openmediavault-omvextrasorg_latest_all5.deb ...
Unpacking openmediavault-omvextrasorg (5.3.6) ...
Setting up openmediavault-omvextrasorg (5.3.6) ...
Updating configuration database ...
dpkg: error processing package openmediavault-omvextrasorg (--install):
 installed openmediavault-omvextrasorg package post-installation script subprocess returned error exit status 1
Processing triggers for openmediavault (5.5.9-1) ...
Updating locale files ...
Updating file permissions ...
Purging internal cache ...
Restarting engine daemon ...
Errors were encountered while processing:
 openmediavault-omvextrasorg
Installing other dependencies ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up openmediavault-omvextrasorg (5.3.6) ...
Updating configuration database ...
dpkg: error processing package openmediavault-omvextrasorg (--configure):
 installed openmediavault-omvextrasorg package post-installation script subprocess returned error exit status 1
Processing triggers for openmediavault (5.5.9-1) ...
Updating locale files ...
Updating file permissions ...
Purging internal cache ...
Restarting engine daemon ...
Errors were encountered while processing:
 openmediavault-omvextrasorg
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

The install of openmediavault-omvextrasorg on a fresh OMV 5 install does not seems to work. Everything is fresh new with latest versions. Dependencies are OK.

```
dpkg -l|grep -i openmedia
ii  openmediavault                  5.5.9-1                             all          openmediavault - The open network attached storage solution
ii  openmediavault-keyring          1.0                                 all          GnuPG archive keys of the OpenMediaVault archive
iF  openmediavault-omvextrasorg     5.3.6                               all          OMV-Extras.org Package Repositories for OpenMediaVault
```

But still, omvextra install fails.

**Comment by ryecoaaron** [comment]
What is the output of: omv-salt deploy run omvextras

**Comment by NoxInmortus** [comment]
Hello @ryecoaaron 

```
 omv-salt deploy run omvextras 
debian:
----------
          ID: configure_apt_sources_list_omvextras
    Function: file.managed
        Name: /etc/apt/sources.list.d/omvextras.list
      Result: False
     Comment: Unable to manage file: none of the specified sources were found
     Started: 18:25:13.731186
    Duration: 102.241 ms
     Changes:   
----------
          ID: configure_apt_pref_omvextras
    Function: file.managed
        Name: /etc/apt/preferences.d/omvextras.pref
      Result: False
     Comment: Unable to manage file: none of the specified sources were found
     Started: 18:25:13.833957
    Duration: 13.14 ms
     Changes:   
----------
          ID: refresh_database_apt
    Function: module.run
        Name: pkg.refresh_db
      Result: True
     Comment: 
     Started: 18:25:13.849496
    Duration: 2.514 ms
     Changes:   

Summary for debian
------------
Succeeded: 1
Failed:    2
------------
Total states run:     3
Total run time: 117.895 ms
```

**Comment by ryecoaaron** [comment]
I really have no idea what causes this. It isn’t an omvextras issue.  Try:
/usr/bin/salt-call —local saltutil.clear_cache
omv-salt stage run prepare
omv-salt deploy run omvextras

**Comment by NoxInmortus** [comment]
@ryecoaaron Well thanks you because it did resolve my issue!

**Comment by Eyap53** [comment]
Got exact same problem. Also solved with @ryecoaaron commands.

**Comment by ktraglin** [comment]
This solution may have worked with previous versions of RaspberryPI-OS, but the problem persists with the latest version (2021-01-11-raspios-buster-armhf-lite).  Has anyone found a solution for this latest version?

**Comment by ryecoaaron** [comment]
The RPi OS version shouldn't matter.  And if you are installing the latest omv-extras will install even if error and more verbose.  Where is the output from your problem?

**Comment by ktraglin** [comment]
> The RPi OS version shouldn't matter. And if you are installing the latest omv-extras will install even if error and more verbose. Where is the output from your problem?

It was the same as in the first post from "NoxInmortus".

**Comment by ryecoaaron** [comment]
You must be getting an old version then.  5.5.1 cannot fail at that point anymore - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/blob/master/debian/postinst#L38

**Comment by ktraglin** [comment]
I used this command to download and run the script according to instructions from "https://wiki.omv-extras.org/doku.php?id=installing_omv5_raspberry_pi"
 "wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install | sudo bash "
I'll try again.
